<?php

$contentType = 'offre_cooperation';

$correspondance = [
    "title|text",
    "field_cooperation|taxosTitle|cooperation",
    "field_date_valide|date|/",
    "field_date|date|/",
    "field_typologie_gal|taxosTitle|types_territoire_coop",
    "field_caracteristiques|taxosTitle|caracteristiques_territoires",
    "field_themes_coop|taxosTitle|themes_coop",
    "field_rubriques|taxosTitle|rubriques",
    "field_themes|taxosTitle|themes",
    "field_echelons|taxosTitle|echelons",
    "field_fonds|taxosTitle|fonds",
    "field_annee|taxoTitle|annees",
    "body|textarea",
    "field_objectifs|textarea",
    "field_description|textarea",
    "field_recommandations|textarea",
    "field_langues|textarea",
    "field_etat|text",
    "field_region|text",
    "field_gal_nom|text",
    "field_nom_contact|text",
    "field_email|text",
    "field_telephone|text",
    "field_contact|textarea",
    "field_body_en|textarea",
    "field_description_en|textarea",
    "field_objectifs_en|textarea",
    "field_recommandations_en|textarea",
    "field_langues_en|textarea",
    "field_etat_en|text",
    "field_region_en|text",
    "field_gal_nom_en|text",
    "field_nom_contact_en|text",
    "field_email_en|text",
    "field_telephone_en|text",
    "field_adresse_en|textarea",    
];